[package]
name = "vmtranslator"
version = "0.1.0"
authors = ["satu-n <49983831+satu-n@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
combine = "4.5"
